### PR TITLE
Login Logout

### PR DESCRIPTION
**Pull request by dangnv-1299**
## Related Tickets
[- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/53516)](https://edu-redmine.sun-asterisk.vn/issues/53516)

## WHAT (optional)
- Init layout có navbar đăng nhập, hồ sơ user
- Login logout
- signup

## Evidence (Screenshot or Video)
Screenshot from 2022-09-21 14-17-09

### CODE REVIEW

**Comment by dangnv-1299** [comment]
ready

**Comment by dangnv-1299** [comment]
ready

**Comment by dangnv-1299** [comment]
ready

**Comment by dangnv-1299** [comment]
ready

**Comment by dangnv-1299** [comment]
ready

**Comment by manhnt-0960** [comment]
ready

**Comment by manhnt-0960** [comment]
commented

**Pull request merged**
